sudo: required
dist: precise
language: go

go:
  - 1.6.2
  - tip

env:
  global:
    - TEST_ZABBIX_URL=http://localhost:80/zabbix/api_jsonrpc.php
    - TEST_ZABBIX_USER=Admin
    - TEST_ZABBIX_PASSWORD=zabbix
    - TEST_ZABBIX_VERBOSE=1
  matrix:
    - ZABBIX_VERSION=2.0
    - ZABBIX_VERSION=2.2
    - ZABBIX_VERSION=2.4

before_install: sudo hostname travis && sudo -E ./setup.rb
